name: CI & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Build & test with Maven
        run: mvn clean verify

      - name: Publish code coverage report
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml

      - name: Deploy to Artifactory
        env:
          MAVEN_USERNAME: ${{ secrets.ARTIFACTORY_USER }}
          MAVEN_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        run: mvn deploy \
               -DaltDeploymentRepository=artifactory::default::${ARTIFACTORY_URL}/libs-release-local \
               -s settings.xml

      # settings.xml-t beágyazhatod inline vagy használhatsz action-t, pl. jfrog/setup-jfrog-cli
